### ISSUE TITLE
Add banner for calls to action during v0.5

### ISSUE THREAD

**Issue by olliegilbey** [interchainio/dev-portal-docsite#17]
To gather feedback, and inform that the site is in progress - a thin top banner would go a long way to inform people to use the feedback form, and to click the Ask AI button.

Proposed Text:

"The Interchain Stack Docsite is in MVP state; please submit comments with the feedback button. The Ask AI button is also very powerful."

**Comment by Reecepbcups** [comment]
Added https://github.com/interchainio/dev-portal-docsite/pull/9/commits/387f74cf62813580f89e14c6d2707ac168db4c9c and deployed
