### ISSUE TITLE
the ask ai button has bad ux

### ISSUE THREAD

**Issue by Reecepbcups** [interchainio/dev-portal-docsite#18]
It’s grayed out in a bad way. maybe black / white vs gray. gray is terrible due to standard design principals, where gray means not clickable or interactable.

![Image](https://github.com/user-attachments/assets/d389e137-2377-4e8c-9371-c6e1af9371c5)

![Image](https://github.com/user-attachments/assets/ec21eeef-f995-4543-8009-14894f9e342e)

**Comment by olliegilbey** [comment]
I'm not seeing the same, it should be white #FFF, in both dark and light mode.

![Image](https://github.com/user-attachments/assets/307c6d34-685f-4e21-b516-8f6889463c21)
![Image](https://github.com/user-attachments/assets/9d44e1c7-957b-451d-90c4-20863f9f8fb3)

**Comment by Reecepbcups** [comment]
It is actually in reference to this button - will add more context to the issue

![Image](https://github.com/user-attachments/assets/d389e137-2377-4e8c-9371-c6e1af9371c5)

![Image](https://github.com/user-attachments/assets/ec21eeef-f995-4543-8009-14894f9e342e)


The grayed out arrow behavior is meh and seems you can't press it in either instance

**Comment by Reecepbcups** [comment]
Found at: https://docs.kapa.ai/integrations/website-widget/configuration#style-parameters-optional
